ros2/rosidl_typesupport

rosidl_default_generators/package.xml, rosidl_default_generators/rosidl_default_generators-extras.cmake.in, rosidl_default_runtime/CMakeLists.txt, rosidl_default_runtime/package.xml, rosidl_typesupport_cpp/CMakeLists.txt, rosidl_typesupport_cpp/bin/rosidl_typesupport_cpp, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/identifier.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/message_type_support.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/message_type_support_dispatch.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support_dispatch.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/type_support_map.h, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/visibility_control.h, rosidl_typesupport_cpp/package.xml, rosidl_typesupport_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in, rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py, rosidl_typesupport_cpp/src/identifier.cpp
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=1943)](http://ci.ros2.org/job/ci_linux/1943/)
* MacOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1498)](http://ci.ros2.org/job/ci_osx/1498/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=1891)](http://ci.ros2.org/job/ci_windows/1891/)
=> add rosidl_typesupport_cpp

rosidl_typesupport_c/include/rosidl_typesupport_c/service_type_support_dispatch.h, rosidl_typesupport_c/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support_dispatch.hpp, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
=> update service type support header name

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_c/package.xml, rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in, rosidl_typesupport_cpp/CMakeLists.txt, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake, rosidl_typesupport_cpp/package.xml, rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in
Same approach as ros2/rosidl#266. Replacing #14. Connect to ros2/ros2#468.
=> use ament_cmake_ros

rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
=> use CMAKE_CURRENT_BINARY_DIR for arguments json

rosidl_typesupport_c/include/rosidl_typesupport_c/identifier.h, rosidl_typesupport_c/include/rosidl_typesupport_c/message_type_support_dispatch.h, rosidl_typesupport_c/include/rosidl_typesupport_c/service_type_support_dispatch.h, rosidl_typesupport_c/include/rosidl_typesupport_c/visibility_control.h, rosidl_typesupport_c/resource/rosidl_typesupport_c__visibility_control.h.in, rosidl_typesupport_c/src/message_type_support_dispatch.cpp, rosidl_typesupport_c/src/service_type_support_dispatch.cpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/visibility_control.h
=> Change #if to #ifdef.

rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_action_interfaces.cmake, rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_action_interfaces.cmake, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
This is for compatibility with uncrustify v0.68.
Connects to ros2/rosidl#340
Connects to ament/uncrustify_vendor#3
=> Change uncrustify max line length to 0

rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
The improved error message was helpful when debugging something else.
=> include available typesuppports in error message

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_cpp/CMakeLists.txt
Partially targets https://github.com/ros2/ros2/issues/658
=> Using ament_target_dependencies where possible

rosidl_typesupport_c/bin/rosidl_typesupport_c, rosidl_typesupport_cpp/bin/rosidl_typesupport_cpp
=> remove usage of UnknownMessageType

rosidl_typesupport_c/resource/msg__type_support.cpp.em, rosidl_typesupport_c/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/resource/action__type_support.cpp.em, rosidl_typesupport_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
=> update code to match refactoring of rosidl definitions

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_cpp/CMakeLists.txt
=> [backport dashing] Make Poco optional again

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_c/package.xml, rosidl_typesupport_cpp/CMakeLists.txt, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake, rosidl_typesupport_cpp/package.xml
This PR is related to the changes introduced in this PR https://github.com/ros2/rosidl/pull/442. The full process can be followed here https://github.com/ros2/rosidl/issues/443
Signed-off-by: ahcorde <ahcorde@gmail.com>
=> added rosidl_runtime c depencency

rosidl_typesupport_c/resource/action__type_support.c.em, rosidl_typesupport_c/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/action__type_support.cpp.em, rosidl_typesupport_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
=> update includes to use non-entry point headers from detail subdir

rosidl_typesupport_c/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
Together with ros2/rosidl#470 fixes #469.
=> fix build with single introspection typesupport

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_cpp/CMakeLists.txt
=> export targets in a addition to include directories / libraries

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_cpp/CMakeLists.txt, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
=> export targets in addition to include directories / libraries

README.md, rosidl_typesupport_c/Doxyfile, rosidl_typesupport_c/README.md, rosidl_typesupport_c/include/rosidl_typesupport_c/identifier.h, rosidl_typesupport_c/include/rosidl_typesupport_c/message_type_support_dispatch.h, rosidl_typesupport_c/include/rosidl_typesupport_c/service_type_support_dispatch.h, rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h, rosidl_typesupport_c/rosidl_typesupport_c/__init__.py, rosidl_typesupport_cpp/Doxyfile, rosidl_typesupport_cpp/README.md, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/identifier.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/message_type_support_dispatch.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support_dispatch.hpp, rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/type_support_map.h, rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py
As part of the effort to increase these packages to QL 1, this PR adds API documentation to the public functions and types.
=> API documentation for public functions

rosidl_typesupport_c/QUALITY_DECLARATION.md, rosidl_typesupport_cpp/QUALITY_DECLARATION.md
This PR adds a link to REP-2006 (the Security Vulnerability Declaration) to the Quality Declaration for this repository.
Connects to ros2/ros2#924.
=> QD Security Vulnerability Declaration: REP 2006

rosidl_typesupport_c/src/type_support_dispatch.hpp
Signed-off-by: lobotuerk <jtlorente@ekumenlabs.com>
=> Catch exception from has_symbol

rosidl_typesupport_c/package.xml, rosidl_typesupport_cpp/package.xml
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Update the maintainers.

rosidl_typesupport_c/CMakeLists.txt, rosidl_typesupport_c/package.xml, rosidl_typesupport_c/src/type_support_dispatch.hpp, rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp, rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp, rosidl_typesupport_cpp/CMakeLists.txt, rosidl_typesupport_cpp/src/type_support_dispatch.hpp, rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp, rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
It depends on: 
- https://github.com/ros2/rcutils/pull/297/
=> [Backport Foxy] Increased rosidl_typesupport_c and rosidl_typesupport_cpp coverage

rosidl_typesupport_c/QUALITY_DECLARATION.md, rosidl_typesupport_cpp/QUALITY_DECLARATION.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
=> Update some missing QL statements to 2

rosidl_typesupport_c/QUALITY_DECLARATION.md, rosidl_typesupport_c/README.md, rosidl_typesupport_cpp/QUALITY_DECLARATION.md, rosidl_typesupport_cpp/README.md
=> Update QD to QL 1

rosidl_typesupport_c/QUALITY_DECLARATION.md, rosidl_typesupport_c/README.md, rosidl_typesupport_cpp/QUALITY_DECLARATION.md, rosidl_typesupport_cpp/README.md
=> [foxy] Update QD to QL 1

rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h
typesupport_identidentifier -> typesupport_identifier
Signed-off-by: Shane Loretz <sloretz@openrobotics.org>
=> Typo typesupport_identidentifier

rosidl_typesupport_c/QUALITY_DECLARATION.md, rosidl_typesupport_cpp/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
=> Updating Quality Declaration

rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
Precisely what the title says. Connected to https://github.com/ros2/rosidl/pull/601.
=> Bundle and ensure the exportation of rosidl generated targets

rosidl_typesupport_c/package.xml, rosidl_typesupport_c/resource/action__type_support.c.em, rosidl_typesupport_c/resource/msg__type_support.cpp.em, rosidl_typesupport_c/resource/srv__type_support.cpp.em, rosidl_typesupport_c/rosidl_typesupport_c/__init__.py, rosidl_typesupport_cpp/package.xml, rosidl_typesupport_cpp/resource/action__type_support.cpp.em, rosidl_typesupport_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py
Depends on https://github.com/ros2/rosidl/pull/696
=> Replace rosidl_cmake imports with rosidl_pycommon

rosidl_typesupport_c/resource/action__type_support.c.em, rosidl_typesupport_c/resource/msg__type_support.cpp.em, rosidl_typesupport_c/resource/srv__type_support.cpp.em, rosidl_typesupport_c/test/benchmark/benchmark_type_support_dispatch.cpp, rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp, rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp, rosidl_typesupport_c/test/test_type_support.c, rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake, rosidl_typesupport_cpp/package.xml, rosidl_typesupport_cpp/resource/action__type_support.cpp.em, rosidl_typesupport_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_cpp/test/benchmark/benchmark_type_support_dispatch.cpp, rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp, rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp, rosidl_typesupport_cpp/test/test_type_support.cpp
Part of ros2/ros2#1159
Depends on https://github.com/ros2/rosidl/pull/727 (and is bundled with)
=> Type Description Nested Support

rosidl_typesupport_c/src/type_support_dispatch.hpp, rosidl_typesupport_cpp/src/type_support_dispatch.hpp
address https://github.com/ros2/rmw_fastrtps/issues/742
=> compare string contents but string pointer addresses.

rosidl_typesupport_c/CHANGELOG.rst, rosidl_typesupport_c/package.xml, rosidl_typesupport_cpp/CHANGELOG.rst, rosidl_typesupport_cpp/package.xml, rosidl_typesupport_tests/CHANGELOG.rst, rosidl_typesupport_tests/package.xml
Release changelog and version bump. I will folow up with the tag and bloom once this is merged.
NOTE: We might wanna rebase to keep the commits as per the history in this repo.
=> Rolling release.
