- rosidl_default_generators/package.xml
- rosidl_default_generators/rosidl_default_generators-extras.cmake.in
- rosidl_default_runtime/CMakeLists.txt
- rosidl_default_runtime/package.xml
- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/bin/rosidl_typesupport_c
- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/include/rosidl_typesupport_c/identifier.h
- rosidl_typesupport_c/include/rosidl_typesupport_c/message_type_support_dispatch.h
- rosidl_typesupport_c/include/rosidl_typesupport_c/service_type_support_dispatch.h
- rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h
- rosidl_typesupport_c/include/rosidl_typesupport_c/visibility_control.h
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/resource/msg__type_support.cpp.em
- rosidl_typesupport_c/resource/rosidl_typesupport_c__visibility_control.h.in
- rosidl_typesupport_c/resource/srv__type_support.cpp.em
- rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in
- rosidl_typesupport_c/rosidl_typesupport_c/__init__.py
- rosidl_typesupport_c/src/identifier.c
- rosidl_typesupport_c/src/message_type_support_dispatch.cpp
- rosidl_typesupport_c/src/service_type_support_dispatch.cpp
- rosidl_typesupport_c/src/type_support_dispatch.cpp
- rosidl_typesupport_c/src/type_support_dispatch.hpp
Similar to the recent changes to the C++ typesupport this PR together with the many referenced ones applies similar changes to the C typesupport:
* all users of the typesupport always use `rosidl_typesupport_c`
* `rosidl_typesupport_c` stores a dictionary of available typesupports
* the rmw implementation use a function from the typesupport struct to extract the specific typesupport they support
Linux ([![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2131)](http://ci.ros2.org/job/ci_linux/2131/)) and Mac OS ([![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1633)](http://ci.ros2.org/job/ci_osx/1633/)) are looking good. I am still looking into Windows.
But while I am doing that I am already asking for review of this and all referenced PRs (either …
> typesupport c reloaded

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/bin/rosidl_typesupport_c
- rosidl_typesupport_c/cmake/get_used_typesupports.cmake
- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/resource/msg__type_support.cpp.em
- rosidl_typesupport_c/resource/srv__type_support.cpp.em
- rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in
- rosidl_typesupport_c/rosidl_typesupport_c/__init__.py
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/bin/rosidl_typesupport_cpp
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
- rosidl_typesupport_cpp/package.xml
- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
- rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in
- rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py
If all available rmw implementation use the same typesupport (which should "always" be the case for a single rmw implementation) `rosidl_typesupport_c|cpp` uses that specific typesupport directly (including linking against the specific typesupport) instead of generating a dictionary and dispatching to the requested typesupport at runtime (using `dlopen`).
Only FastRTPS:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2166)](http://ci.ros2.org/job/ci_linux/2166/)
* Mac OS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1649)](http://ci.ros2.org/job/ci_osx/1649/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2169)](http://ci.ros2.org/job/ci_windows/2169/)
Only Connext:
* Linux [![Build …
> shortcut for single typesupport

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in
- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
- rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
If Poco is not available the rosidl_typesupport_c|cpp libraries are being built without it. Downstream interface packages can then only be built if they select a single typesupport.
Only FastRTPS:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2174)](http://ci.ros2.org/job/ci_linux/2174/)
* Mac OS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1656)](http://ci.ros2.org/job/ci_osx/1656/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2176)](http://ci.ros2.org/job/ci_windows/2176/)
Only Connext:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2175)](http://ci.ros2.org/job/ci_linux/2175/)
* Mac OS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=165 …
> make poco optional

- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
This message should help in cases where the library isn't found or doesn't contain the expected symbol.
> add hopefully helpful error message

- rosidl_default_runtime/package.xml
The Python code of each message uses a function from `rosidl_generator_py`.
@nuclearsandwich This needs to be rebloomed for beta 2 after being merged.
> add missing dependency

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
Follow up of #362.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2880)](http://ci.ros2.org/job/ci_linux/2880/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=371)](http://ci.ros2.org/job/ci_linux-aarch64/371/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2324)](http://ci.ros2.org/job/ci_osx/2324/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3008)](http://ci.ros2.org/job/ci_windows/3008/)
Ready for review.
> fix setting CXX_STANDARD for message generation

- rosidl_default_generators/CMakeLists.txt
- rosidl_default_generators/package.xml
- rosidl_default_generators/rosidl_default_generators-extras.cmake.in
- rosidl_default_runtime/package.xml
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
Add group dependencies on typesupport packages to make it easier to add additional rmw implementations to a workspace.
Since these PRs only touch the manifests I only triggered a single CI build:
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4212)](https://ci.ros2.org/job/ci_linux/4212/)
> add group_depends for typesupport

- rosidl_default_generators/CMakeLists.txt
- rosidl_default_generators/package.xml
- rosidl_default_generators/rosidl_default_generators-extras.cmake.in
- rosidl_default_runtime/CMakeLists.txt
- rosidl_default_runtime/package.xml
- rosidl_default_runtime/rosidl_default_runtime-extras.cmake.in
- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/package.xml
Requires ros2/rosidl#283.
The rosidl generator | runtime packages declare being a member of a group as well as register themselves at the resource index.
Additionally the default packages depend on their group and in CMake collect the available generator | runtime packages from the resource index instead of using a hard coded list (while keeping the mandatory ones explicitly listed in the manifest).
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4659)](https://ci.ros2.org/job/ci_linux/4659/)
> add and use groups for generator and runtime packages

- rosidl_default_generators/package.xml
- rosidl_default_runtime/package.xml
This change will reduce the amount of effort required to ensure that vendor typesupport packages are optional for end-users. And it cleans up our dependency tree a little with caveats*
The vendor typesupport packages are also members in the respective groups rosidl_typesupport_c{,pp}_packages and thus will still be directly depended upon by this package for source builds.
Here's a graph of the tree from an example message package (std_msgs) to the vendor typesupport packages.
*These graphs do not consider group dependencies which I think re-introduce the "overspecified" dependencies from the before image below.
Before: ![deps before](https://user-images.githubusercontent.com/358882/41629719-0c8caa92-73f9-11e8-931e-1b39a313136a.png)
---
After: ![deps …
> Remove direct dependencies on vendor typesupport packages.

- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
Connects to ros2/rmw_implementation#41
This change is motivated by the discussion in https://github.com/ros2/rmw_implementation/pull/41#discussion_r197289719
The build_export dependencies on the vendor typesupport packages will be moved into Suggests in the debian/control templates after bloom generates them.
> Prepare dependencies for bouncy release.

- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
exposes a new symbol in the each message library in order to load the cpp typesupport.
```
rosidl_typesupport_cpp__get_message_type_support_handle__<pkg_name>__msg__<message_type>
```
This then allows to open the library (e.g. via Poco) and get the typesupport in order to create a ROS 2 publisher or subscriber:
``` c++
#include <unistd.h>
#include "ament_index_cpp/get_resources.hpp"
#include "ament_index_cpp/get_package_prefix.hpp"
#include "Poco/SharedLibrary.h"
#include "rcl/rcl.h"
#include "rcutils/snprintf.h"
#include "rosidl_generator_c/message_type_support_struct.h"
std::string get_typesupport_library(const std::string & package_name)
{
const char * env_var;
char separator;
const char * filename_prefix;
const char * filename_extension;
#ifdef _WIN32
env_var = "PATH";
separator = …
```
> expose symbol for cpp typesupport

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
The target dependency won't exist at cmake configure time before the first build if it is generated, so don't `FATAL_ERROR` in that case.
connects to ros2/rcl_interfaces#47
> Allow generated IDL files

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_action_interfaces.cmake
- rosidl_typesupport_c/resource/action__type_support.c.em
- rosidl_typesupport_c/rosidl_typesupport_c/__init__.py
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_action_interfaces.cmake
- rosidl_typesupport_cpp/resource/action__type_support.cpp.em
- rosidl_typesupport_cpp/resource/rosidl_typesupport_cpp__action_visibility_control.h.in
FYI @sservulo here's a PR targeted at your branch with some additions to make `rosidl_generate_interfaces()` try to generate the action type supports.
connects to ros2/rcl_interfaces#48
> Generate action type supports

- rosidl_typesupport_c/resource/msg__type_support.cpp.em
- rosidl_typesupport_c/resource/srv__type_support.cpp.em
- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
Small fix, pending CI on https://github.com/ros2/rosidl_typesupport_connext/pull/18.
> Fix include prefix in C & C++ typesupport templates.

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_action_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_action_interfaces.cmake
Fixes ros2/build_cop#154. Had to reduce the name length for action targets a bit. I did so everywhere for consistency.
> Reduces action interfaces CMake target name length to please Windows.

- rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py
Works around a limitation where the generation for the overall action doesn't know about messages in the same package. Even with this line commented out, the action fields are still validated individually when the messages and services that make up an action are generated.
Fixes ros2/rosidl#348
This PR should be backported to crystal
> Don't validate overall actions

- rosidl_typesupport_cpp/rosidl_typesupport_cpp/__init__.py
This is a backport of #44. Note: this branch is just a fast-forward to 183782ee9945009473fed1d67b8a5a3e602db722 since there are no other changes since crystal release. ~~As such it can be merged instead of squash/merged.~~ [*Edit: looks like the right button is rebase and merge since merge forces a merge commit*](https://help.github.com/en/articles/about-pull-request-merges)
ros2/ros2#656
> [Crystal patch 3 backport] Don't validate overall actions (#44)

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_cpp/CMakeLists.txt
Poco library is only needed if multiple DDS implementations are to be
supported. For 'static' builds with a single DDS in the sources, Poco
can be omitted.
Closes #53
Signed-off-by: Sean Kelly <sean@seankelly.dev>
Please consider for backport to dashing
> Make Poco optional again

- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
Support for OpenSplice has been discontinued from ROS Foxy onwards.
Find a discussion here: https://discourse.ros.org/t/opensplice-move-to-eclipse-cyclone-dds-in-ros-2/12370
> Remove OpenSplice dependencies

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_cpp/CMakeLists.txt
Poco library is only needed if multiple DDS implementations are to be
supported. For 'static' builds with a single DDS in the sources, Poco
can be omitted.
Closes #53
Signed-off-by: Sean Kelly <sean@seankelly.dev>
> [eloquent backport] Make Poco optional again (#54)

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in
- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
- rosidl_typesupport_cpp/package.xml
- rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
As part of the effort to remove Poco dependency described in this issue https://github.com/ros2/ros2/issues/867 this PR makes use of the recent changes in rcutils https://github.com/ros2/rcutils/pull/215 to load, unload and get symbols from shared libraries instead of using Poco.
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Removed poco dependency

- rosidl_typesupport_c/include/rosidl_typesupport_c/message_type_support_dispatch.h
- rosidl_typesupport_c/include/rosidl_typesupport_c/service_type_support_dispatch.h
- rosidl_typesupport_c/resource/msg__type_support.cpp.em
- rosidl_typesupport_c/resource/srv__type_support.cpp.em
- rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/message_type_support_dispatch.hpp
- rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support_dispatch.hpp
- rosidl_typesupport_cpp/resource/action__type_support.cpp.em
- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
> rename rosidl_generator_c namespace to rosidl_runtime_c

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
Fixes https://github.com/osrf/buildfarmer/issues/29#issuecomment-619070630. Related to ros2/ros2#904.
Linux CI builds up to `builtin_interfaces` with only CycloneDDS:
* Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10487)](https://ci.ros2.org/job/ci_linux/10487/)
* After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10493)](https://ci.ros2.org/job/ci_linux/10493/)
> fix single typesupport build exposing build directory in include dirs

- rosidl_typesupport_c/QUALITY_DECLARATION.md
- rosidl_typesupport_cpp/QUALITY_DECLARATION.md
This PR adds current quality declarations for both packages as QL 4. With PR #63 and #64 they can almost be QL 3 or even QL 2, but the version will also need to be bumped to 1.0.
> Current quality level declarations

- rosidl_typesupport_c/Doxyfile
- rosidl_typesupport_c/QUALITY_DECLARATION.md
- rosidl_typesupport_c/README.md
- rosidl_typesupport_c/docs/FEATURES.md
- rosidl_typesupport_cpp/Doxyfile
- rosidl_typesupport_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_cpp/README.md
- rosidl_typesupport_cpp/docs/FEATURES.md
This fills out the feature documentation in the READMEs of these two packages. I'm also uncommenting the TAGFILES for rosidl_runtime_c/cpp which have been recently added.
> Completing feature documentation

- rosidl_typesupport_c/QUALITY_DECLARATION.md
- rosidl_typesupport_cpp/QUALITY_DECLARATION.md
Upon review, the API documentation is actually sufficient in this package. This now brings up the documentation status of this package to QL 1 pending public hosting of the API docs.
> Update API documentation and QDs

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
- rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in
Similar to https://github.com/ros2/rosidl/pull/485.
Required by https://github.com/ament/ament_cmake/pull/256.
> Force extension points to be registered in order

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_type_support.c
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_type_support.cpp
These tests were behaving differently under release mode than debug mode, which is how they were originally tested and evaluated. I'm not entirely sure of the full cause of the issue or why it worked in debug mode but not release. As far as I can tell the functions defined in `test_type_support.c` and `test_type_support.cpp` were simple void functions, but after loading their libraries` type_support_dispatch` called those functions and assigned their result to a pointer which was then returned, and that always returned null on gcc release. Even stranger, printing out the address of sym with std::cout in `type_support_dispatch` allowed the test to pass. It seems likely to me that the original code was causing undefined behavior and gcc's optimizations caused a different result than debug …
> Addresses test failures in release mode

- rosidl_typesupport_c/QUALITY_DECLARATION.md
- rosidl_typesupport_cpp/QUALITY_DECLARATION.md
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Update Quality Declarations to level 3.

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
`rosidl_typesupport_c` code had some rethrown exceptions which were inside extern c functions. I believe, but not entirely sure, this is not recommended since there is no way for the C code to handle them and they would otherwise be fatal errors. MSVC's optimizer was also treating this code strangely when I tried to catch the exception from a c++ test and would get different results by adding unrelated changes.
Example failure with fault injection test:
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11853)](https://ci.ros2.org/job/ci_windows/11853/)
> Remove rethrow in extern c code

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
This adds unit test macros and fault injection to rosidl_typesupport_c and rosidl_typesupport_cpp. With these fault injections, coverage can get to 100%. I'll post CI results soon.
> Add fault injection macros and unit tests

- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
On bad environment lookups. As shown by https://github.com/ros2/rcutils/pull/292.
> Handle rcpputils::find_library_path() failure.

- rosidl_typesupport_c/QUALITY_DECLARATION.md
- rosidl_typesupport_c/README.md
- rosidl_typesupport_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_cpp/README.md
All the dependencies are level 2 or higher, so these packages can be bumped to level 2.
Also added links to the performance tests added in https://github.com/ros2/rosidl_typesupport/pull/84.
> Update QDs to Quality Level 2

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/test/benchmark/benchmark_type_support_dispatch.cpp
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/package.xml
- rosidl_typesupport_cpp/test/benchmark/benchmark_type_support_dispatch.cpp
* Added benchmark test to rosidl_typesupport_c
Signed-off-by: ahcorde <ahcorde@gmail.com>
* Added benchmark test to rosidl_typesupport_cpp
Signed-off-by: ahcorde <ahcorde@gmail.com>
* reset heap counters
Signed-off-by: ahcorde <ahcorde@gmail.com>
* Replace BENCHMARK_DEFINE_F and BENCHMARK_REGISTER_F with BENCHMARK_F
Signed-off-by: ahcorde <ahcorde@gmail.com>
* Fixed test
Signed-off-by: ahcorde <ahcorde@gmail.com>
> [Backport Foxy] Added benchmark test to rosidl_typesupport_c/cpp (#84)

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/test/mocking_utils/patch.hpp
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
This PR boosts coverage for this package to 100% after #86 was merged by mocking the exception thrown by `rcpputils::SharedLibrary::get_symbol`
> Add mock for rcutils_get_symbol failure

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/test/mocking_utils/patch.hpp
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
This backports #93 for 100% of `rosidl_typesupport_c`
Testing `--packages-select rosidl_typesupport_c` on foxy
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12980)](http://ci.ros2.org/job/ci_linux/12980/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7932)](http://ci.ros2.org/job/ci_linux-aarch64/7932/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10705)](http://ci.ros2.org/job/ci_osx/10705/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12958)](http://ci.ros2.org/job/ci_windows/12958/)
> [foxy backport] Add mock for rcutils_get_symbol failure (#93)

- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/type_support_map.h
- rosidl_typesupport_cpp/package.xml
- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/test/benchmark/benchmark_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
Port of #81 to Foxy branch.
Testing in foxy CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12304)](http://ci.ros2.org/job/ci_linux/12304/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7276)](http://ci.ros2.org/job/ci_linux-aarch64/7276/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10020)](http://ci.ros2.org/job/ci_osx/10020/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12202)](http://ci.ros2.org/job/ci_windows/12202/)
> [Foxy backport]: De-deplicate type_support_map.h header

- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
This showed up as a false positive from clang static analysis. It's because it doesn't realize that gtest `ASSERT_*` macros will return. Clang does allow for `analyzer_noreturn` annotations to help it understand, but I believe that's only on functions. Clang does recognize standard `assert` statements though, so I thought that would be the simplest solution here.
Example
```
/home/brawner/workspace/ros2_master/src/ros2/rosidl_typesupport/rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp:117:15: warning: Called C++ object pointer is null
EXPECT_TRUE(lib->has_symbol("test_message_type_support"));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/brawner/workspace/ros2_master/install/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:1969:23: note: expanded from macro …
```
> Explicitly check lib pointer for null

- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/message_type_support_dispatch.hpp
- rosidl_typesupport_cpp/include/rosidl_typesupport_cpp/service_type_support_dispatch.hpp
- rosidl_typesupport_cpp/src/message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/src/service_type_support_dispatch.cpp
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
While working on #98, I stumbled upon this inconsistency in error handling within typesupport handle functions. 
These functions are eventually called by `rmw` implementations with no consideration for potential exceptions. If we add that no API documentation mentions exceptions and that some of these APIs even have C linkage, I'm inclined to assume these functions shouldn't ever throw to begin with.
> Ensure typesupport handle functions do not throw.

- rosidl_typesupport_c/src/type_support_dispatch.hpp
- rosidl_typesupport_cpp/src/type_support_dispatch.hpp
Connected to https://github.com/ros2/rcutils/pull/320. By deferring path resolution to the dynamic linker, RPATHs and RUNPATHs entries as well as LD_LIBRARY_PATH and PATH envvars are dealt with the standard way. Pre-linked and pre-loaded libraries are also honored. 
CI up to `test_communication`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13267)](http://ci.ros2.org/job/ci_linux/13267/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8198)](http://ci.ros2.org/job/ci_linux-aarch64/8198/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10987)](http://ci.ros2.org/job/ci_osx/10987/) (known test failure)
* Windows [![Build …
> Defer path resolution of rosidl typesupport libraries to dynamic linker.

- rosidl_typesupport_c/bin/rosidl_typesupport_c
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_c/rosidl_typesupport_c/__init__.py
- rosidl_typesupport_c/rosidl_typesupport_c/cli.py
- rosidl_typesupport_c/setup.cfg
> Expose C typesupport generation via rosidl generate CLI

- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
This PR removes dependencies from `rosidl_typesupport_connext_c`, 
and `rosidl_typesupport_connext_cpp`, since they will both become no longer needed once `rmw_connext_cpp` is replaced by `rmw_connextdds`.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.
> Remove dependencies from Connext type support

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_c/rosidl_typesupport_c/cli.py
- rosidl_typesupport_c/test/msg/Test.msg
- rosidl_typesupport_c/test/test_cli_extension.py
- rosidl_typesupport_cpp/CMakeLists.txt
- rosidl_typesupport_cpp/rosidl_typesupport_cpp/cli.py
- rosidl_typesupport_cpp/test/msg/Test.msg
- rosidl_typesupport_cpp/test/test_cli_extension.py
This fixes issues I overlooked in #104 and #105. It also adds smoke tests that I should've added back then. Changes should be backportable to Galactic.
CI up `rosidl_typesupport_c` and  `rosidl_typesupport_cpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14719)](http://ci.ros2.org/job/ci_linux/14719/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9471)](http://ci.ros2.org/job/ci_linux-aarch64/9471/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12386)](http://ci.ros2.org/job/ci_osx/12386/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14865)](http://ci.ros2.org/job/ci_windows/14865/)
> Fix C and C++ typesupports CLI extensions

- rosidl_typesupport_c/rosidl_typesupport_c/cli.py
- rosidl_typesupport_c/test/test_cli_extension.py
- rosidl_typesupport_cpp/rosidl_typesupport_cpp/cli.py
- rosidl_typesupport_cpp/test/test_cli_extension.py
This patch allows the list of available typesupports to be narrowed down prior to generating C and C++ dynamic typesupport loading data structure through the `rosidl` CLI. Depends on https://github.com/ros2/rosidl/pull/597. Built on top of #111.
CI up to `rosidl_typesupport_c` and `rosidl_typesupport_cpp`:
CI up `rosidl_cli`, `rosidl_typesupport_c`, `rosidl_typesupport_cpp`, and `rosidl_generator_py`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14724)](http://ci.ros2.org/job/ci_linux/14724/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9476)](http://ci.ros2.org/job/ci_linux-aarch64/9476/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12391)](http://ci.ros2.org/job/ci_osx/1 …
> Support available typesupport specification in CLI extensions 

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
Precisely what the title says. This patch rolls back #113. While it doesn't affect downstream builds per se, it does go down a path that is incompatible with how ROS 2 binaries are built.
> Revert "Bundle and ensure the exportation of rosidl generated targets (#113)"

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
- rosidl_typesupport_cpp/package.xml
Alternative to https://github.com/ros2/rosidl/pull/615
I think with both https://github.com/ament/ament_cmake/pull/355 and https://github.com/ros2/rosidl/pull/612 being merged yesterday, two sources of packages internally calling `find_package(PythonInterp)` got removed, but their CI's were run at different times. This replaces the implicit `PythonInterp` dependency with an explicit finding of `Python3`.
> Use FindPython3 in typesupport packages

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_cpp/CMakeLists.txt
Part of https://github.com/ros2/ros2/issues/1150 - this installs resource_retriever's header files to a unique directory in a merged workspace.
> Install headers to include/${PROJECT_NAME}

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
This fixes a bug introduced by ros2/rosidl_typesupport#123
`target_link_libraries()` requires all uses either use the keyword version or the all plain version. #123 updated to the keyword version but missed this spot that's only excercised when a only a single typesupport is used.
I'm able to trigger this bug with:
```
colcon build --packages-up-to sensor_msgs --packages-ignore rosidl_generator_cpp rosidl_typesupport_cpp rosidl_typesupport_connext_cpp rosidl_typesupport_fastrtps_cpp rosidl_typesupport_introspection_cpp rosidl_runtime_cpp rosidl_typesupport_fastrtps_c rosidl_generator_py
```
@Blast545 FYI as I'm sure there would be a nightly job or two broken because of this if it weren't for other issues with the Jammy transition.
> Use target_link_libraries(... PRIVATE ...) in single typesupport case

- rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h
This PR is a prototype for the service introspection REP (https://github.com/ros-infrastructure/rep/pull/360) implementing the proposed single serialized message approach (https://github.com/ros-infrastructure/rep/pull/360#discussion_r902987531).
This PR wraps `#include <cstddef>` in `rosidl_typesupport_c/include/rosidl_typesupport_c/type_support_map.h` so that `rcl` can access `type_support_map_t` 
See: https://github.com/ros2/rcl/pull/990
For instructions on how to build and run this see the meta-ticket https://github.com/ros2/ros2/issues/1285.
Resolves https://github.com/ros2/ros2/issues/1285
> [service introspection] Guard `#include <cstddef>` when being included from a `c` source

- rosidl_typesupport_c/CMakeLists.txt
- rosidl_typesupport_cpp/CMakeLists.txt
The two reasons to do this are:
1. So that we can compile rosidl_typesupport with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
2. So we can build with a newer version of gtest which requires this.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Update rosidl_typesupport to C++17.

- rosidl_typesupport_tests/CMakeLists.txt
- rosidl_typesupport_tests/package.xml
Otherwise, when building it just for RMWs with introspection it fails to build saying it needs rosidl_generator_cpp.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
Goes along with https://github.com/ros2/rosidl/pull/724 , and fixes the issue in https://github.com/ros2/ros2/issues/1285#issuecomment-1419791566
> Make rosidl_typesupport_tests depend on rosidl_generator_cpp.

- rosidl_typesupport_tests/CMakeLists.txt
- rosidl_typesupport_tests/package.xml
- rosidl_typesupport_tests/test/rosidl_typesupport_c/test_service_typesupport.cpp
- rosidl_typesupport_tests/test/rosidl_typesupport_cpp/test_service_typesupport.cpp
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
After (https://github.com/ros2/rosidl_typesupport/pull/127) we have new 2 failing tests in Rolling CycloneDDS:
[projectroot.test_service_typesupport_cpp](https://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_jammy_amd64/351/testReport/junit/(root)/projectroot/test_service_typesupport_cpp/) log output:
<details>
```
-- run_test.py: invoking following command in '/tmp/ws/build_isolated/rosidl_typesupport_tests':
- /tmp/ws/build_isolated/rosidl_typesupport_tests/test_service_typesupport_cpp --gtest_output=xml:/tmp/ws/test_results/rosidl_typesupport_tests/test_service_typesupport_cpp.gtest.xml
Running main() from /tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 3 tests from 1 …
```
> Fix Typesupport Introspection tests

- rosidl_typesupport_c/test/benchmark/benchmark_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/benchmark/benchmark_type_support_dispatch.cpp
This is just to keep clang static analysis happy.
> Mark benchmark _ as UNUSED.

- rosidl_typesupport_c/resource/msg__type_support.cpp.em
- rosidl_typesupport_c/resource/srv__type_support.cpp.em
- rosidl_typesupport_c/test/benchmark/benchmark_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_c/test/test_type_support.c
- rosidl_typesupport_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
- rosidl_typesupport_cpp/test/benchmark/benchmark_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_message_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_service_type_support_dispatch.cpp
- rosidl_typesupport_cpp/test/test_type_support.cpp
Depends on ros2/rosidl#729 (coupled - must be merged together)
Part of ros2/ros2#1159
Fill out new type_hash and message_type_support fields on generated `rosidl_message_type_support_t` and `rosidl_service_type_support_t` structs.
> Type hashes in typesupport (rep2011)

- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
In particular, rosidl_typesupport_cpp depends on rosidl_generator_type_description when expanding templates, so it should have an exec_depend here.
Also, rosidl_typesupport_c depends on rosidl_generator_c when expanding templates, so it also should have an exec_depend.
This fixes the two bugs listed in #138 .  @Crola1702 FYI
> Fix rosidl_typesupport_c/cpp exec dependencies.

- rosidl_typesupport_cpp/resource/action__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
Currently, only message type support contains a C interface to dynamically load the type support from a library.
This PR adds a C interface for services and actions.
New PR since the previous fork was unfortunately deleted and could not be rebased. For discussions see #114 .
> [RePR from #114] Fixed missing C interfaces to obtain service and action type support.

- rosidl_typesupport_cpp/resource/action__type_support.cpp.em
- rosidl_typesupport_cpp/resource/srv__type_support.cpp.em
Backport of #143 for foxy. See #114 for discussion.
Interfaces are declared in ros2/rosidl#744
> [foxy backport] Added C interfaces to obtain service and action type support.

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
Related to ros2/rosidl#743
`set_target_properties` does not append to values, it only sets them. `target_compile_options` on the other hand appends to any preexisting values.
Because of that, `rosidl_typesupport_cpp` C++ target was overriding user provided compiler options, which hid (for example) `-Wdeprecated` warnings in generated code in `nav2_msgs`.
> Don't override user provided compile definitions

- rosidl_typesupport_c/cmake/rosidl_typesupport_c_generate_interfaces.cmake
- rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
The comment in the commit explains the reasoning behind it.
This must be merged before https://github.com/ros2/ros2/pull/1524 ; see that pull request for more information about this change.
> Set hints to find the python version we actually want.

- rosidl_typesupport_tests/test/rosidl_typesupport_c/test_service_typesupport.cpp
Newer uncrustify is more strict about long lines.  Just disable checking on these long lines.
> Suppress uncrustify on long lines.

- rosidl_typesupport_c/test/test_type_support.c
- rosidl_typesupport_cpp/test/test_type_support.cpp
There are new warnings on CI related with this compiler option `strict-prototypes`
https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1860/gcc/new/
> Fixed warnings - strict-prototypes

- rosidl_typesupport_c/package.xml
- rosidl_typesupport_cpp/package.xml
See ros-infrastructure/catkin_pkg#369
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20943)](http://ci.ros2.org/job/ci_linux/20943/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15234)](http://ci.ros2.org/job/ci_linux-aarch64/15234/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21617)](http://ci.ros2.org/job/ci_windows/21617/)
> Add mechanism to disable workaround for dependency groups
